{
  "sksl": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 u_resolution;\nuniform vec2 delta;\nuniform shader u_tex0;\nuniform half2 u_tex0_size;\n\nvec4 fragColor;\n\nfloat sigma2_color;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nfloat FLT_flutter_local_Lum(vec3 c)\n{\n    return ((0.2989999949932098388671875 * c.x) + (0.58700001239776611328125 * c.y)) + (0.114000000059604644775390625 * c.z);\n}\n\nfloat FLT_flutter_local_random(vec3 scale, float seed)\n{\n    return fract((sin(dot(flutter_FragCoord.xyz + vec3(seed), scale)) * 43758.546875) + seed);\n}\n\nvoid FLT_main()\n{\n    sigma2_color = 25.0;\n    vec2 fragCoord = FLT_flutter_local_FlutterFragCoord();\n    vec2 st = FLT_flutter_local_FlutterFragCoord() / u_resolution;\n    vec3 center_color = u_tex0.eval(u_tex0_size *  st).xyz;\n    vec3 color = center_color;\n    float total = 1.0;\n    vec3 param = center_color;\n    float center_lum = FLT_flutter_local_Lum(param);\n    vec3 param_1 = vec3(12.98980045318603515625, 78.233001708984375, 151.71820068359375);\n    float param_2 = 0.0;\n    float offset = FLT_flutter_local_random(param_1, param_2);\n    for (float t = -20.0; t <= 20.0; t += 1.0)\n    {\n        float percent = ((t + offset) - 0.5) / 20.0;\n        float weight = 1.0 - abs(percent);\n        vec3 tmp_color = u_tex0.eval(u_tex0_size *  st + (delta * percent)).xyz;\n        vec3 param_3 = tmp_color;\n        float diff_color = FLT_flutter_local_Lum(param_3) - center_lum;\n        weight *= exp(-min((diff_color * diff_color) * sigma2_color, 10.0));\n        color += (tmp_color * weight);\n        total += weight;\n    }\n    vec4 res = vec4(color / vec3(total), total / 20.0);\n    fragColor = clamp(res, vec4(0.0), vec4(1.0));\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
  "stage": 1,
  "target_platform": 2,
  "uniforms": [
    {
      "array_elements": 0,
      "bit_width": 32,
      "columns": 1,
      "location": 0,
      "name": "u_resolution",
      "rows": 2,
      "type": 10
    },
    {
      "array_elements": 0,
      "bit_width": 0,
      "columns": 1,
      "location": 1,
      "name": "u_tex0",
      "rows": 1,
      "type": 12
    },
    {
      "array_elements": 0,
      "bit_width": 32,
      "columns": 1,
      "location": 2,
      "name": "delta",
      "rows": 2,
      "type": 10
    }
  ]
}