{
  "sksl": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 u_resolution;\nuniform float xs;\nuniform float ys;\nuniform float r;\nuniform float axis;\nuniform shader u_tex0;\nuniform half2 u_tex0_size;\n\nvec4 fragColor;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nvoid FLT_main()\n{\n    vec2 fragCoord = FLT_flutter_local_FlutterFragCoord();\n    vec2 st = FLT_flutter_local_FlutterFragCoord() / u_resolution;\n    float rr = r * r;\n    vec2 p = (vec2(1.0) + st) * 0.5;\n    vec4 col = vec4(0.0);\n    float w0 = 0.5134999752044677734375 / pow(r, 0.959999978542327880859375);\n    float d;\n    float w;\n    if (axis == 0.0)\n    {\n        d = 1.0 / xs;\n        float _65 = -r;\n        p.x += (_65 * d);\n        for (float x = _65; x <= r; x += 1.0, p.x += d)\n        {\n            w = w0 * exp(((-x) * x) / (2.0 * rr));\n            col += (u_tex0.eval(u_tex0_size *  st) * w);\n        }\n    }\n    if (axis == 1.0)\n    {\n        d = 1.0 / ys;\n        float _122 = -r;\n        p.y += (_122 * d);\n        for (float y = _122; y <= r; y += 1.0, p.y += d)\n        {\n            w = w0 * exp(((-y) * y) / (2.0 * rr));\n            col += (u_tex0.eval(u_tex0_size *  st) * w);\n        }\n    }\n    fragColor = col;\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
  "stage": 1,
  "target_platform": 2,
  "uniforms": [
    {
      "array_elements": 0,
      "bit_width": 32,
      "columns": 1,
      "location": 0,
      "name": "u_resolution",
      "rows": 2,
      "type": 10
    },
    {
      "array_elements": 0,
      "bit_width": 0,
      "columns": 1,
      "location": 1,
      "name": "u_tex0",
      "rows": 1,
      "type": 12
    },
    {
      "array_elements": 0,
      "bit_width": 32,
      "columns": 1,
      "location": 2,
      "name": "xs",
      "rows": 1,
      "type": 10
    },
    {
      "array_elements": 0,
      "bit_width": 32,
      "columns": 1,
      "location": 3,
      "name": "ys",
      "rows": 1,
      "type": 10
    },
    {
      "array_elements": 0,
      "bit_width": 32,
      "columns": 1,
      "location": 4,
      "name": "r",
      "rows": 1,
      "type": 10
    },
    {
      "array_elements": 0,
      "bit_width": 32,
      "columns": 1,
      "location": 5,
      "name": "axis",
      "rows": 1,
      "type": 10
    }
  ]
}